### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by j2kun** [j2kun/harmonic-phase-space#1]
- [x] Add sliders for non-phase parameters
- [x] Update rendering on slider change
- [x] Mouseover on graph shows plot with three curves and their sum and the max value.
- [x] Mouseover on graph updates with proper parameters as mouse moves
